name: Setup Project
description: Install development tools with mise and get dependencies

inputs:
  tools:
    description: 'Space-separated list of tools to install from mise.toml (e.g., "flutter java")'
    required: false
    default: ''

outputs:
  flutter-version:
    description: 'The Flutter version read from mise.toml'
    value: ${{ steps.mise-versions.outputs.flutter }}

runs:
  using: composite
  steps:
    - name: Parse mise tools to install
      id: parse-tools
      shell: bash
      run: |
        tools="${{ inputs.tools }}"
        # Filter out 'ruby' from tools list (handled separately by setup-ruby)
        mise_tools=$(echo "$tools" | tr ' ' '\n' | grep -v '^ruby$' | xargs)
        echo "mise_tools=$mise_tools" >> $GITHUB_OUTPUT

    - name: Install mise
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
      with:
        install_args: ${{ steps.parse-tools.outputs.mise_tools }}

    - name: Read tool versions
      id: mise-versions
      shell: bash
      run: echo "flutter=$(mise current flutter)" >> $GITHUB_OUTPUT

    - name: Setup Ruby
      if: ${{ contains(inputs.tools, 'ruby') }}
      uses: ruby/setup-ruby@8d27f39a5e7ad39aebbcbd1324f7af020229645c # v1.287.0
      with:
        bundler-cache: true

    - name: Setup Flutter pub cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3
      with:
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        path: ~/.pub-cache
        restore-keys: |
          ${{ runner.os }}-pub-

    - name: Install Flutter dependencies
      shell: bash
      run: flutter pub get --enforce-lockfile
