name: Setup Project
description: Checkout code, read Flutter version, setup Flutter, and get dependencies

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Read Flutter version from .fvmrc
      id: fvm
      shell: bash
      run: echo "version=$(jq -r .flutter .fvmrc)" >> $GITHUB_OUTPUT

    - name: Setup Flutter
      uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2
      with:
        flutter-version: ${{ steps.fvm.outputs.version }}
        cache: true

    - name: Get dependencies
      shell: bash
      run: flutter pub get
