name: Setup Project
description: Install development tools with mise and get dependencies

outputs:
  flutter-version:
    description: 'The Flutter version read from mise.toml'
    value: ${{ steps.mise-versions.outputs.flutter }}

runs:
  using: composite
  steps:
    - name: Install mise
      uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

    - name: Read tool versions
      id: mise-versions
      shell: bash
      run: echo "flutter=$(mise current flutter | awk '{print $2}')" >> $GITHUB_OUTPUT

    - name: Install Flutter dependencies
      shell: bash
      run: flutter pub get --enforce-lockfile

    - name: Install Ruby dependencies
      shell: bash
      env:
        BUNDLE_FROZEN: "true"
      run: bundle install
