# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # Shared keystore configuration
  def keystore_config
    {
      git_url: ENV["MATCH_KEYSTORE_GIT_URL"],
      package_name: "club.ntut.tattoo",
      match_secret: ENV["MATCH_KEYSTORE_SECRET"]
    }
  end

  desc "Build and sign release APK"
  lane :build_apk do
    Dir.chdir("../..") do
      sh("flutter", "build", "apk", "--release", "--split-per-abi")
    end

    # Sign each split APK
    ["armeabi-v7a", "arm64-v8a", "x86_64"].each do |abi|
      match_keystore(
        **keystore_config,
        apk_path: "../build/app/outputs/flutter-apk/app-#{abi}-release.apk"
      )
    end
  end

  desc "Build and sign release AAB"
  lane :build_aab do
    Dir.chdir("../..") do
      sh("flutter", "build", "appbundle", "--release")
    end

    match_keystore(
      **keystore_config,
      aab_path: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
